#!/usr/bin/env python3
"""BC10 production: FONLL B mesons -> B -> K^(i) a -> a four-vector CSVs.

Reuses the HNL FONLL bottom sampler (``hnl/production/fonll``) for the parent B
kinematics at 14 TeV, then does the two-body B -> K_i a decay (HNL
``decay_engine.kinematics.decay_2body``) for every channel of the kaon tower
(model.KAON_TOWER: K, K0*, K*, K1, K2* -- the GKOZ arXiv:2310.03524 channel
set) for both B+ and B0, and keeps the ALP four-vector.  One CSV per ALP mass,
in the HNL combined format

    weight, E, px, py, pz            (headerless, pb at the reference coupling)

so the downstream analysis can consume it through the imported
``analysis.format_bridge.load_combined_csv`` + ``scan_u2`` chain unchanged.  The
per-row weight is the production cross section (pb) at the reference inverse
decay constant ``model.INV_F_REF``:

    weight = 2 * sigma_FONLL(bottom) * frag(B) * BR(B->K_i a)|_ref / n_channel

(the factor 2 covers b and bbar).  Production scales as (1/f)^2, so the
sensitivity scan rescales this single reference weight by u2 = (1/f / 1/f_ref)^2
(see sensitivity.py).  This is the coupling -> production half of the BC10 model
layer; the lifetime and branching fractions live in ``model.py``, while the
published stable-particle templates are generated by
``generate_decay_templates_pythia.py``.

NOTE on columns: the prompt's nominal schema (event,id,pt,eta,phi,momentum,mass)
is the *unweighted* higgs/LLP format.  BC10 is coupling-controlled, so each a
MUST carry a production weight; the HNL (weight,E,px,py,pz) format is therefore
the canonical input and is what the reused load_combined_csv reads.

Usage:
    python -m alp_fermion.alp_production --n-pool 200000
    python -m alp_fermion.alp_production --n-pool 1200000 \
        --high-pt-tilt-scale 5 --nominal-mixture-fraction 0.5
    python -m alp_fermion.alp_production --mass 0.5 1.0 2.0
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

_ALP_ROOT = Path(__file__).resolve().parent
if str(_ALP_ROOT) not in sys.path:
    sys.path.insert(0, str(_ALP_ROOT))

import model  # noqa: E402
from mass_grid import ALP_MASS_GRID  # noqa: E402
from paths import LLP_VECTORS_DIR, add_hnl_to_path  # noqa: E402

add_hnl_to_path()

from config_mass_grid import format_mass_for_filename  # noqa: E402
from production.constants import FRAG_B  # noqa: E402
from production.fonll.fonll_parser import get_sigma_total  # noqa: E402
from production.fonll.meson_sampler import (  # noqa: E402
    sample_meson_4vectors, meson_4vec_from_kinematics,
)
from production.decay_engine.kinematics import decay_2body  # noqa: E402
from production.io import write_llp_csv, write_empty_csv  # noqa: E402


def alp_csv_path(mass, base=LLP_VECTORS_DIR):
    path = base / f"mA_{format_mass_for_filename(mass)}.csv"
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


def _atomic_write(path, weights=None, energy=None, px=None, py=None, pz=None):
    """Write one mass output atomically so ``--resume`` never accepts a partial CSV."""
    temporary = path.with_suffix(path.suffix + ".tmp")
    if weights is None:
        write_empty_csv(temporary)
    else:
        write_llp_csv(temporary, weights, energy, px, py, pz)
    temporary.replace(path)


def _importance_weighted_rate(normalization, pool, indices):
    """Apply the nominal/proposal FONLL density ratio to selected parents."""
    ratios = pool.get("sampling_weight")
    if ratios is None:
        return np.full(len(indices), normalization)
    return normalization * np.asarray(ratios, dtype=float)[indices]


def _partition_parent_indices(n_pool, n_channels, rng):
    """Assign disjoint, random parent samples to each production channel."""
    if n_pool < n_channels:
        raise ValueError("n_pool must be at least the number of channels")
    n_each = n_pool // n_channels
    usable = n_each * n_channels
    permutation = rng.permutation(n_pool)[:usable]
    return permutation.reshape(n_channels, n_each)


def generate(
    masses,
    n_pool,
    seed=42,
    resume=False,
    cbs_amplitude_scale=1.0,
    high_pt_tilt_scale=None,
    nominal_mixture_fraction=0.5,
):
    if cbs_amplitude_scale <= 0.0:
        raise ValueError("cbs_amplitude_scale must be positive")
    rng = np.random.default_rng(seed)
    print(f"Sampling {n_pool} FONLL bottom (pt,y,phi) shape events...", flush=True)
    pool = sample_meson_4vectors(
        n_pool,
        "bottom",
        rng=rng,
        high_pt_tilt_scale=high_pt_tilt_scale,
        nominal_mixture_fraction=nominal_mixture_fraction,
    )
    sigma_b = get_sigma_total("bottom")
    print(f"  sigma_FONLL(bottom) = {sigma_b:.4e} pb", flush=True)

    channels = [(label, pdg, kaon)
                for label, pdg in model.PRODUCTION_PARENTS
                for kaon in model.KAON_TOWER]

    for m_a in masses:
        resonance = model.excluded_light_meson_resonance(m_a)
        if resonance is not None:
            print(
                f"  m_a={m_a:.3f}: skip unsupported {resonance} resonance",
                flush=True,
            )
            continue
        path = alp_csv_path(m_a)
        already_done = resume and path.exists()
        all_w, all_E, all_px, all_py, all_pz = [], [], [], [], []
        parent_indices = _partition_parent_indices(
            n_pool, len(channels), rng,
        )
        for channel_index, (label, pdg, kaon) in enumerate(channels):
            m_B = model.M_BPLUS if label == "B+" else model.M_B0
            m_K = model.kaon_mass(kaon, label)
            if m_a >= m_B - m_K:
                continue
            br = model.br_B_to_Ka(
                m_a, model.INV_F_REF, parent=label, kaon=kaon
            ) * cbs_amplitude_scale**2
            if br <= 0.0:
                continue
            frag = FRAG_B[pdg]
            idx = parent_indices[channel_index]
            n_each = len(idx)
            v = meson_4vec_from_kinematics(
                pool["pt"][idx], pool["y"][idx], pool["phi"][idx], m_B)
            # two-body B -> K_i(m_K) + a(m_a); decay_2body returns (d1=K, d2=a)
            _, a4 = decay_2body(v["E"], v["px"], v["py"], v["pz"],
                                m_B, m_K, m_a, rng=rng)
            w = _importance_weighted_rate(
                2.0 * sigma_b * frag * br / n_each,
                pool,
                idx,
            )
            if not already_done:
                all_w.append(w)
                all_E.append(a4[:, 0]); all_px.append(a4[:, 1])
                all_py.append(a4[:, 2]); all_pz.append(a4[:, 3])

        if already_done:
            print(f"  m_a={m_a:.3f}: already checkpointed -> {path.name}", flush=True)
            continue
        if all_w:
            weights = np.concatenate(all_w)
            _atomic_write(
                path, weights, np.concatenate(all_E), np.concatenate(all_px),
                np.concatenate(all_py), np.concatenate(all_pz),
            )
            print(f"  m_a={m_a:.3f}: {len(weights)} a, "
                  f"sigma_ref={weights.sum():.3e} pb -> {path.name}", flush=True)
        else:
            _atomic_write(path)
            print(f"  m_a={m_a:.3f}: 0 (above B->K a threshold)", flush=True)


def main(argv=None):
    ap = argparse.ArgumentParser(description="BC10 a four-vector production")
    ap.add_argument("--mass", type=float, nargs="+", default=None)
    ap.add_argument("--n-pool", type=int, default=200_000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument(
        "--resume", action="store_true",
        help="keep atomically completed mass CSVs while replaying the RNG stream",
    )
    ap.add_argument(
        "--cbs-amplitude-scale", type=float, default=1.0,
        help="multiply C_bs by this factor (production rates scale as its square)",
    )
    ap.add_argument(
        "--high-pt-tilt-scale",
        type=float,
        default=None,
        help=(
            "importance-sample a nominal/high-pT FONLL mixture tilted by "
            "exp(pT/scale); output weights include the exact p/q correction"
        ),
    )
    ap.add_argument(
        "--nominal-mixture-fraction",
        type=float,
        default=0.5,
        help="nominal fraction of the optional high-pT proposal mixture",
    )
    args = ap.parse_args(argv)
    masses = args.mass if args.mass else ALP_MASS_GRID
    print(f"BC10 production: {len(masses)} masses, n_pool={args.n_pool}")
    print(f"  output -> {LLP_VECTORS_DIR}")
    generate(
        masses, args.n_pool, args.seed,
        resume=args.resume,
        cbs_amplitude_scale=args.cbs_amplitude_scale,
        high_pt_tilt_scale=args.high_pt_tilt_scale,
        nominal_mixture_fraction=args.nominal_mixture_fraction,
    )
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
