"""Core HNL sensitivity engine.

Geometry ray-casting through the GRENDEL mesh, FairShip decay-template loading,
deterministic per-point seeding, hit-event sampling, and the per-(flavor, mass)
acceptance Monte Carlo (:func:`process_mass_point`). Imported both by the
``run_sensitivity`` CLI driver and by the band scripts (``bc_nuisance``,
``channel_breakdown``, ``decay_model_band``), so the shared machinery lives here
rather than inside the driver module.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np

HNL_ROOT = Path(__file__).resolve().parent.parent
if str(HNL_ROOT) not in sys.path:
    sys.path.insert(0, str(HNL_ROOT))

from config_mass_grid import format_mass_for_filename
from production.paths import ANALYSIS_DIR, LLP_VECTORS_DIR, TMP_DIR
from analysis.constants import (
    CMS_ORIGIN,
    L_INT_PB,
    LOG_U2_MAX,
    LOG_U2_MIN,
    N_THRESHOLD,
    N_U2_POINTS,
)
from analysis.exclusion import find_exclusion_band
from analysis.format_bridge import load_combined_csv
from analysis.plot_exclusion import plot_nsignal_vs_u2
from analysis.decay_reco_acceptance import (
    build_event_mc, classify_template_modes, scan_u2)


# FairShip rest-frame decay templates (generated by generate_decay_templates.py);
# their bundle also carries ctau(U^2=1), so no separate ctau/BR_vis table is used.
TEMPLATE_DIR = TMP_DIR / "decay_templates"
# decay positions sampled per hitting event for the acceptance MC
DECAY_SAMPLES = 100

# Single source for the GRENDEL mesh + reconstruction: the higgs analysis's
# grendel_geometry / reco_common (PR #13 on main), shared by the signal MC.
RECO_DIR = HNL_ROOT.parent / "higgs"
GEOM_CACHE_DIR = ANALYSIS_DIR / "geometry_cache"


# =========================================================================
# Geometry: ray-cast through the GRENDEL mesh (lazy import)
# =========================================================================

def _get_mesh():
    """Lazy-import the GRENDEL mesh from the shared ``higgs/`` single source."""
    if not RECO_DIR.exists():
        raise FileNotFoundError(
            f"higgs/ directory not found at {RECO_DIR}.\n"
            "The checkout is incomplete; higgs/grendel_geometry.py is required."
        )
    if str(RECO_DIR) not in sys.path:
        sys.path.insert(0, str(RECO_DIR))
    from grendel_geometry import mesh_fiducial
    return mesh_fiducial


def _eta_phi_to_directions_batch(eta, phi):
    """(eta, phi) arrays -> (N, 3) unit direction vectors."""
    theta = 2.0 * np.arctan(np.exp(-eta))
    dx = np.sin(theta) * np.cos(phi)
    dy = np.sin(theta) * np.sin(phi)
    dz = np.cos(theta)
    return np.column_stack([dx, dy, dz])


def compute_geometry(eta, phi, mesh, origin=CMS_ORIGIN, batch_label=""):
    """Batch ray-cast (eta, phi) directions against the GRENDEL mesh."""
    n = len(eta)
    origin_arr = np.array(origin, dtype=np.float64)
    hits = np.zeros(n, dtype=bool)
    entry_d = np.full(n, np.nan)
    exit_d = np.full(n, np.nan)

    directions = _eta_phi_to_directions_batch(eta, phi)
    candidates = np.where(directions[:, 1] > 0.01)[0]
    n_cand = len(candidates)
    if n_cand == 0:
        return hits, entry_d, exit_d

    print(f"  Batch ray-casting {n_cand}/{n} candidates {batch_label}...",
          flush=True)

    cand_dirs = directions[candidates]
    # Chunk the ray-cast: intersects_location allocates per-ray x per-triangle
    # intermediates, so casting all candidates at once spikes to several GB on
    # the highest-multiplicity (lowest-mass) points. Rays are independent, so
    # batching gives identical results while bounding peak memory.
    GEOM_RAY_CHUNK = 25000
    loc_parts, rid_parts = [], []
    for cs in range(0, n_cand, GEOM_RAY_CHUNK):
        ce = min(cs + GEOM_RAY_CHUNK, n_cand)
        chunk_dirs = cand_dirs[cs:ce]
        chunk_origins = np.tile(origin_arr, (len(chunk_dirs), 1))
        loc_c, rid_c, _ = mesh.ray.intersects_location(
            ray_origins=chunk_origins, ray_directions=chunk_dirs)
        if len(loc_c):
            loc_parts.append(loc_c)
            rid_parts.append(rid_c + cs)  # ray_ids are chunk-local; shift to candidate index

    if not loc_parts:
        print(f"  0/{n} events hit detector", flush=True)
        return hits, entry_d, exit_d
    locations = np.concatenate(loc_parts)
    ray_ids = np.concatenate(rid_parts)

    dists = np.linalg.norm(locations - origin_arr, axis=1)
    order = np.argsort(ray_ids)
    sorted_ray_ids = ray_ids[order]
    sorted_dists = dists[order]

    unique_rays, start_idx, counts = np.unique(
        sorted_ray_ids, return_index=True, return_counts=True)

    valid = counts >= 2
    valid_rays = unique_rays[valid]
    valid_starts = start_idx[valid]
    valid_counts = counts[valid]

    for i in range(len(valid_rays)):
        ray_local = valid_rays[i]
        orig_idx = candidates[ray_local]
        s = valid_starts[i]
        e = s + valid_counts[i]
        ray_dists = sorted_dists[s:e]
        ray_dists.sort()
        hits[orig_idx] = True
        entry_d[orig_idx] = ray_dists[0]
        exit_d[orig_idx] = ray_dists[1]

    n_hits = int(hits.sum())
    print(f"  {n_hits}/{n} events hit detector ({n_hits / n * 100:.2f}%)",
          flush=True)
    if n_hits > 0:
        path_lens = exit_d[hits] - entry_d[hits]
        print(f"  Mean path length: {path_lens.mean():.2f} m", flush=True)
    return hits, entry_d, exit_d


def load_or_compute_geometry(flavor, mass_label, eta, phi, mesh, force=False,
                             source_mtime=None):
    """Load cached geometry or compute + cache as NPZ.

    The cache is keyed on (flavor, mass) only, so a stale NPZ is invalidated
    whenever the source 4-vector CSV is newer than the cache (``source_mtime``):
    regenerating a combined CSV forces a fresh ray-cast instead of serving old
    hits. Geometry-code changes are not tracked by mtime -- pass --force-geometry
    after editing the GRENDEL mesh.
    """
    cache_dir = GEOM_CACHE_DIR / flavor
    cache_path = cache_dir / f"geom_{mass_label}.npz"

    fresh = cache_path.exists() and not force
    if fresh and source_mtime is not None:
        fresh = cache_path.stat().st_mtime >= source_mtime
    if fresh:
        data = np.load(cache_path)
        return data["hits"].astype(bool), data["entry_d"], data["exit_d"]

    hits, entry_d, exit_d = compute_geometry(
        eta, phi, mesh, CMS_ORIGIN, batch_label=f"[{flavor}/{mass_label}]")

    cache_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(cache_path, hits=hits, entry_d=entry_d, exit_d=exit_d)
    return hits, entry_d, exit_d


# =========================================================================
# FairShip decay templates
# =========================================================================

def load_decay_templates(flavor, mass_label):
    """Cached rest-frame decay templates for (flavor, mass), or None if absent."""
    path = TEMPLATE_DIR / flavor / f"templates_{mass_label}.npz"
    if not path.exists():
        return None
    return np.load(path)


def _seed_for(flavor, mass_label, seed_salt=""):
    """Deterministic per-point RNG seed (order-independent, reproducible)."""
    key = f"{flavor}/{mass_label}"
    if seed_salt:
        key += f"/{seed_salt}"
    h = hashlib.md5(key.encode()).digest()
    return int.from_bytes(h[:4], "little")


# =========================================================================
# Single-point processing
# =========================================================================

def _select_hit_sample(idx, weights, max_hit_events, rng):
    """Return hit indices and scan weights for exact or approximate evaluation."""
    weights = np.asarray(weights, dtype=float)
    if max_hit_events is None or max_hit_events <= 0 or len(idx) <= max_hit_events:
        return idx, weights, "exact"

    total_weight = float(weights.sum())
    if total_weight > 0.0 and np.isfinite(total_weight):
        probabilities = weights / total_weight
        sampled_idx = rng.choice(
            idx, size=int(max_hit_events), replace=True, p=probabilities)
        sampled_weights = np.full(
            len(sampled_idx), total_weight / len(sampled_idx), dtype=float)
        return sampled_idx, sampled_weights, "weighted_resample"

    sampled_pos = rng.choice(len(idx), size=int(max_hit_events), replace=False)
    sampled_idx = idx[sampled_pos]
    sampled_weights = np.asarray(weights[sampled_pos], dtype=float)
    sampled_weights *= len(idx) / max(len(sampled_idx), 1)
    return sampled_idx, sampled_weights, "uniform_rescale"


def process_mass_point(flavor, mass, mesh,
                       force_geometry=False, save_diagnostic=False,
                       decay_samples=DECAY_SAMPLES, max_hit_events=None,
                       event_chunk=None, seed_salt="",
                       width_delta=None, had_frac=None):
    """Process one (flavor, mass) point and return its exclusion band."""
    mass_label = format_mass_for_filename(mass)
    csv_path = LLP_VECTORS_DIR / flavor / "combined" / f"mN_{mass_label}.csv"

    if not csv_path.exists() or csv_path.stat().st_size == 0:
        return None

    data = load_combined_csv(csv_path, mass)
    n_events = len(data["weight"])
    if n_events == 0:
        return None

    hits, entry_d, exit_d = load_or_compute_geometry(
        flavor, mass_label, data["eta"], data["phi"], mesh,
        force=force_geometry, source_mtime=csv_path.stat().st_mtime)

    n_hits = int(hits.sum())
    if n_hits == 0:
        return {
            "mass_GeV": mass, "flavor": flavor,
            "u2_min": np.nan, "u2_max": np.nan,
            "u2_min_open": False, "u2_max_open": False,
            "peak_N": 0.0, "peak_u2": np.nan,
            "has_sensitivity": False, "n_events": n_events, "n_hits": 0,
        }

    templates = load_decay_templates(flavor, mass_label)
    if templates is None:
        print(f"  NOTE: no decay templates for {flavor}/{mass_label}; "
              "run generate_decay_templates.py first. Skipping.")
        return None
    ctau_u2_1 = float(templates["ctau_m_u2eq1"])
    if ctau_u2_1 <= 0:
        return None

    # Build the acceptance MC for the hitting events only.
    idx_all = np.where(hits & np.isfinite(entry_d) & np.isfinite(exit_d))[0]
    rng = np.random.default_rng(_seed_for(flavor, mass_label, seed_salt))
    idx, scan_weights, hit_estimator = _select_hit_sample(
        idx_all, data["weight"][idx_all], max_hit_events, rng)
    if len(idx) == 0:
        return {
            "mass_GeV": mass, "flavor": flavor,
            "u2_min": np.nan, "u2_max": np.nan,
            "u2_min_open": False, "u2_max_open": False,
            "peak_N": 0.0, "peak_u2": np.nan,
            "has_sensitivity": False, "n_events": n_events,
            "n_hits": n_hits, "n_hits_eval": 0,
            "decay_samples": decay_samples,
            "hit_estimator": hit_estimator,
            "event_chunk": event_chunk, "seed_salt": seed_salt,
        }

    entry_sel = entry_d[idx]
    exit_sel = exit_d[idx]
    beta_gamma_sel = data["beta_gamma"][idx]
    direction = _eta_phi_to_directions_batch(
        data["eta"][idx], data["phi"][idx])
    p_mag = beta_gamma_sel * mass
    energy = data["gamma"][idx] * mass
    p4 = np.column_stack([energy, p_mag[:, None] * direction])
    u2_grid = np.logspace(LOG_U2_MIN, LOG_U2_MAX, N_U2_POINTS)
    N_grid = np.zeros(len(u2_grid))

    # Exact event evaluation can transiently allocate O(n_hits * n_samples)
    # reconstruction arrays. Process bounded event chunks and add their yields;
    # scan_u2 is linear in events, so this changes memory use, not the estimator.
    chunk_size = len(idx)
    if event_chunk is not None and event_chunk > 0:
        chunk_size = min(int(event_chunk), len(idx))

    # Avoid repeatedly decompressing the NPZ arrays for every event chunk.
    if hasattr(templates, "files"):
        archive = templates
        templates = {name: archive[name] for name in archive.files}
        archive.close()

    varied_N = {}
    mode_is_had = None
    if width_delta:
        mode_is_had = classify_template_modes(templates)
        varied_N = {"lo": np.zeros(len(u2_grid)),
                    "hi": np.zeros(len(u2_grid))}

    for start in range(0, len(idx), chunk_size):
        stop = min(start + chunk_size, len(idx))
        sl = slice(start, stop)
        d, passed, tmpl_idx = build_event_mc(
            p4[sl], direction[sl], entry_sel[sl], exit_sel[sl],
            templates, decay_samples, rng, origin=CMS_ORIGIN)
        _, N_part = scan_u2(
            d, passed, exit_sel[sl] - entry_sel[sl], scan_weights[sl],
            beta_gamma_sel[sl], ctau_u2_1, L_INT_PB, u2_grid)
        N_grid += N_part

        if width_delta:
            hf = had_frac if had_frac else 1.0
            samp_had = mode_is_had[tmpl_idx]
            for tag, gscale in (("lo", 1.0 + width_delta),
                                ("hi", 1.0 - width_delta)):
                w_lep = 1.0 / gscale
                w_had = (1.0 + (gscale - 1.0) / hf) / gscale
                sample_w = np.where(samp_had, w_had, w_lep)
                _, N_part_v = scan_u2(
                    d, passed, exit_sel[sl] - entry_sel[sl],
                    scan_weights[sl], beta_gamma_sel[sl],
                    ctau_u2_1 / gscale, L_INT_PB, u2_grid,
                    sample_w=sample_w)
                varied_N[tag] += N_part_v

    result = find_exclusion_band(u2_grid, N_grid, N_THRESHOLD)

    # Decay-model band: ONE seam-derived width nuisance delta(m) driven
    # coherently through BOTH legs on the SAME built MC (no re-ray, reco frozen):
    #   - lifetime leg: Gamma_tot*(1+/-delta) -> ctau/(1+/-delta);
    #   - composition leg: Gamma_had +/- delta*Gamma_tot reweights the
    #     hadronic-vs-leptonic template mix (w_had/w_lep below), shifting vis_frac.
    # The two partly self-cancel (Gamma up -> shorter ctau but more visible
    # hadronic modes), so they are co-varied in one scan -- never quadrature.
    if width_delta:
        hf = had_frac if had_frac else 1.0
        for tag in ("lo", "hi"):
            r_v = find_exclusion_band(u2_grid, varied_N[tag], N_THRESHOLD)
            result[f"u2_max_dm_{tag}"] = r_v["u2_max"]
            result[f"u2_min_dm_{tag}"] = r_v["u2_min"]
        result["width_delta"] = width_delta
        result["had_frac"] = hf

    result["mass_GeV"] = mass
    result["flavor"] = flavor
    result["n_events"] = n_events
    result["n_hits"] = n_hits
    result["n_hits_eval"] = len(idx)
    result["decay_samples"] = decay_samples
    result["hit_estimator"] = hit_estimator
    result["event_chunk"] = event_chunk
    result["seed_salt"] = seed_salt

    if save_diagnostic:
        diag_dir = ANALYSIS_DIR / "diagnostics"
        plot_nsignal_vs_u2(u2_grid, N_grid, mass, flavor, diag_dir)

    return result
