#!/usr/bin/env python3
"""
hnl/analysis/run_sensitivity.py

Main driver: compute HNL sensitivity from the combined 4-vector CSVs that
``hnl/production/`` writes, and produce the (m_N, U^2) money plot.

Default flavor is Umu only (HNL pattern 010 -- the muon-mixing scenario).

Usage examples:

    python -m analysis.run_sensitivity                       # Umu, full grid
    python -m analysis.run_sensitivity --flavor Ue Umu       # multi-flavor
    python -m analysis.run_sensitivity --mass 1.0 2.0        # custom masses
    python -m analysis.run_sensitivity --workers 3           # parallel workers
    python -m analysis.run_sensitivity --plot-only           # re-plot only

Inputs (read via ``production.paths``):

    {LLP_VECTORS_DIR}/{flavor}/combined/mN_{mass}.csv    -- 4-vectors per point
    {TMP_DIR}/decay_templates/{flavor}/templates_{mass}.npz  -- FairShip decays + ctau
    ../higgs/grendel_geometry.py  (sibling package, PR #13)  -- shared mesh

Outputs:

    {ANALYSIS_DIR}/hnl_sensitivity.csv
    {ANALYSIS_DIR}/hnl_exclusion.{pdf,png}
    {ANALYSIS_DIR}/geometry_cache/{flavor}/geom_{mass}.npz
    {ANALYSIS_DIR}/diagnostics/                          -- with --diagnostics
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

HNL_ROOT = Path(__file__).resolve().parent.parent
if str(HNL_ROOT) not in sys.path:
    sys.path.insert(0, str(HNL_ROOT))

from config_mass_grid import MASS_GRID, format_mass_for_filename
from production.paths import ANALYSIS_DIR, LLP_VECTORS_DIR, TMP_DIR

from analysis.constants import (
    CMS_ORIGIN,
    DEFAULT_FLAVORS,
    FLAVORS,
    ANALYSIS_MASS_MAX,
    L_INT_PB,
    LOG_U2_MAX,
    LOG_U2_MIN,
    N_THRESHOLD,
    N_U2_POINTS,
)
from analysis.exclusion import find_exclusion_band
from analysis.format_bridge import load_combined_csv
from analysis.plot_exclusion import plot_exclusion, plot_nsignal_vs_u2
from analysis.decay_reco_acceptance import build_event_mc, scan_u2

# FairShip rest-frame decay templates (generated by generate_decay_templates.py);
# their bundle also carries ctau(U^2=1), so no separate ctau/BR_vis table is used.
TEMPLATE_DIR = TMP_DIR / "decay_templates"
# decay positions sampled per hitting event for the acceptance MC
DECAY_SAMPLES = 100

# Single source for the GRENDEL mesh + reconstruction: the higgs analysis's
# grendel_geometry / reco_common (PR #13 on main), shared by the signal MC.
RECO_DIR = HNL_ROOT.parent / "higgs"
GEOM_CACHE_DIR = ANALYSIS_DIR / "geometry_cache"


# =========================================================================
# Geometry: ray-cast through the GRENDEL mesh (lazy import)
# =========================================================================

def _get_mesh():
    """Lazy-import the GRENDEL mesh from the shared ``higgs/`` single source."""
    if not RECO_DIR.exists():
        raise FileNotFoundError(
            f"higgs/ directory not found at {RECO_DIR}.\n"
            "The checkout is incomplete; higgs/grendel_geometry.py is required."
        )
    if str(RECO_DIR) not in sys.path:
        sys.path.insert(0, str(RECO_DIR))
    from grendel_geometry import mesh_fiducial
    return mesh_fiducial


def _eta_phi_to_directions_batch(eta, phi):
    """(eta, phi) arrays -> (N, 3) unit direction vectors."""
    theta = 2.0 * np.arctan(np.exp(-eta))
    dx = np.sin(theta) * np.cos(phi)
    dy = np.sin(theta) * np.sin(phi)
    dz = np.cos(theta)
    return np.column_stack([dx, dy, dz])


def compute_geometry(eta, phi, mesh, origin=CMS_ORIGIN, batch_label=""):
    """Batch ray-cast (eta, phi) directions against the GRENDEL mesh."""
    n = len(eta)
    origin_arr = np.array(origin, dtype=np.float64)
    hits = np.zeros(n, dtype=bool)
    entry_d = np.full(n, np.nan)
    exit_d = np.full(n, np.nan)

    directions = _eta_phi_to_directions_batch(eta, phi)
    candidates = np.where(directions[:, 1] > 0.01)[0]
    n_cand = len(candidates)
    if n_cand == 0:
        return hits, entry_d, exit_d

    print(f"  Batch ray-casting {n_cand}/{n} candidates {batch_label}...",
          flush=True)

    cand_dirs = directions[candidates]
    # Chunk the ray-cast: intersects_location allocates per-ray x per-triangle
    # intermediates, so casting all candidates at once spikes to several GB on
    # the highest-multiplicity (lowest-mass) points. Rays are independent, so
    # batching gives identical results while bounding peak memory.
    GEOM_RAY_CHUNK = 25000
    loc_parts, rid_parts = [], []
    for cs in range(0, n_cand, GEOM_RAY_CHUNK):
        ce = min(cs + GEOM_RAY_CHUNK, n_cand)
        chunk_dirs = cand_dirs[cs:ce]
        chunk_origins = np.tile(origin_arr, (len(chunk_dirs), 1))
        loc_c, rid_c, _ = mesh.ray.intersects_location(
            ray_origins=chunk_origins, ray_directions=chunk_dirs)
        if len(loc_c):
            loc_parts.append(loc_c)
            rid_parts.append(rid_c + cs)  # ray_ids are chunk-local; shift to candidate index

    if not loc_parts:
        print(f"  0/{n} events hit detector", flush=True)
        return hits, entry_d, exit_d
    locations = np.concatenate(loc_parts)
    ray_ids = np.concatenate(rid_parts)

    dists = np.linalg.norm(locations - origin_arr, axis=1)
    order = np.argsort(ray_ids)
    sorted_ray_ids = ray_ids[order]
    sorted_dists = dists[order]

    unique_rays, start_idx, counts = np.unique(
        sorted_ray_ids, return_index=True, return_counts=True)

    valid = counts >= 2
    valid_rays = unique_rays[valid]
    valid_starts = start_idx[valid]
    valid_counts = counts[valid]

    for i in range(len(valid_rays)):
        ray_local = valid_rays[i]
        orig_idx = candidates[ray_local]
        s = valid_starts[i]
        e = s + valid_counts[i]
        ray_dists = sorted_dists[s:e]
        ray_dists.sort()
        hits[orig_idx] = True
        entry_d[orig_idx] = ray_dists[0]
        exit_d[orig_idx] = ray_dists[1]

    n_hits = int(hits.sum())
    print(f"  {n_hits}/{n} events hit detector ({n_hits / n * 100:.2f}%)",
          flush=True)
    if n_hits > 0:
        path_lens = exit_d[hits] - entry_d[hits]
        print(f"  Mean path length: {path_lens.mean():.2f} m", flush=True)
    return hits, entry_d, exit_d


def load_or_compute_geometry(flavor, mass_label, eta, phi, mesh, force=False):
    """Load cached geometry or compute + cache as NPZ."""
    cache_dir = GEOM_CACHE_DIR / flavor
    cache_path = cache_dir / f"geom_{mass_label}.npz"

    if cache_path.exists() and not force:
        data = np.load(cache_path)
        return data["hits"].astype(bool), data["entry_d"], data["exit_d"]

    hits, entry_d, exit_d = compute_geometry(
        eta, phi, mesh, CMS_ORIGIN, batch_label=f"[{flavor}/{mass_label}]")

    cache_dir.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(cache_path, hits=hits, entry_d=entry_d, exit_d=exit_d)
    return hits, entry_d, exit_d


# =========================================================================
# FairShip decay templates
# =========================================================================

def load_decay_templates(flavor, mass_label):
    """Cached rest-frame decay templates for (flavor, mass), or None if absent."""
    path = TEMPLATE_DIR / flavor / f"templates_{mass_label}.npz"
    if not path.exists():
        return None
    return np.load(path)


def _seed_for(flavor, mass_label):
    """Deterministic per-point RNG seed (order-independent, reproducible)."""
    h = hashlib.md5(f"{flavor}/{mass_label}".encode()).digest()
    return int.from_bytes(h[:4], "little")


# =========================================================================
# Single-point processing
# =========================================================================

def process_mass_point(flavor, mass, mesh,
                       force_geometry=False, save_diagnostic=False):
    """Process one (flavor, mass) point and return its exclusion band."""
    mass_label = format_mass_for_filename(mass)
    csv_path = LLP_VECTORS_DIR / flavor / "combined" / f"mN_{mass_label}.csv"

    if not csv_path.exists() or csv_path.stat().st_size == 0:
        return None

    data = load_combined_csv(csv_path, mass)
    n_events = len(data["weight"])
    if n_events == 0:
        return None

    hits, entry_d, exit_d = load_or_compute_geometry(
        flavor, mass_label, data["eta"], data["phi"], mesh,
        force=force_geometry)

    n_hits = int(hits.sum())
    if n_hits == 0:
        return {
            "mass_GeV": mass, "flavor": flavor,
            "u2_min": np.nan, "u2_max": np.nan,
            "u2_min_open": False, "u2_max_open": False,
            "peak_N": 0.0, "peak_u2": np.nan,
            "has_sensitivity": False, "n_events": n_events, "n_hits": 0,
        }

    templates = load_decay_templates(flavor, mass_label)
    if templates is None:
        print(f"  NOTE: no decay templates for {flavor}/{mass_label}; "
              "run generate_decay_templates.py first. Skipping.")
        return None
    ctau_u2_1 = float(templates["ctau_m_u2eq1"])
    if ctau_u2_1 <= 0:
        return None

    # Build the acceptance MC for the hitting events only.
    idx = np.where(hits & np.isfinite(entry_d) & np.isfinite(exit_d))[0]
    direction = _eta_phi_to_directions_batch(data["eta"][idx], data["phi"][idx])
    p_mag = data["beta_gamma"][idx] * mass
    energy = data["gamma"][idx] * mass
    p4 = np.column_stack([energy, p_mag[:, None] * direction])
    rng = np.random.default_rng(_seed_for(flavor, mass_label))
    d, passed = build_event_mc(
        p4, direction, entry_d[idx], exit_d[idx], templates, DECAY_SAMPLES,
        rng, origin=CMS_ORIGIN)

    u2_grid = np.logspace(LOG_U2_MIN, LOG_U2_MAX, N_U2_POINTS)
    u2_grid, N_grid = scan_u2(
        d, passed, exit_d[idx] - entry_d[idx], data["weight"][idx],
        data["beta_gamma"][idx], ctau_u2_1, L_INT_PB, u2_grid)

    result = find_exclusion_band(u2_grid, N_grid, N_THRESHOLD)
    result["mass_GeV"] = mass
    result["flavor"] = flavor
    result["n_events"] = n_events
    result["n_hits"] = n_hits

    if save_diagnostic:
        diag_dir = ANALYSIS_DIR / "diagnostics"
        plot_nsignal_vs_u2(u2_grid, N_grid, mass, flavor, diag_dir)

    return result


# =========================================================================
# Parallel worker plumbing
# =========================================================================

_WORKER_MESH = None


def _worker_init():
    global _WORKER_MESH
    _WORKER_MESH = _get_mesh()


def _worker_process_point(args):
    flavor, mass, force_geom, save_diag = args
    t0 = time.time()
    result = process_mass_point(
        flavor, mass, _WORKER_MESH,
        force_geometry=force_geom, save_diagnostic=save_diag)
    elapsed = time.time() - t0
    mass_label = format_mass_for_filename(mass)
    tag = f"{flavor}/mN_{mass_label}"
    if result and result.get("has_sensitivity"):
        print(f"  {tag}: sensitivity found ({elapsed:.1f}s)", flush=True)
    elif result:
        print(f"  {tag}: done, no sensitivity ({elapsed:.1f}s)", flush=True)
    else:
        print(f"  {tag}: skipped ({elapsed:.1f}s)", flush=True)
    return result


# =========================================================================
# Driver
# =========================================================================

def run(flavors, masses, n_workers=1, force_geometry=False,
        save_diagnostics=False):
    ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)
    GEOM_CACHE_DIR.mkdir(parents=True, exist_ok=True)

    work_items = []
    for flavor in flavors:
        for mass in masses:
            work_items.append((flavor, mass, force_geometry, save_diagnostics))

    n_total = len(work_items)
    print(f"\nProcessing {n_total} mass points "
          f"with {n_workers} worker(s)...\n", flush=True)

    t_start = time.time()
    results = []
    status_path = ANALYSIS_DIR / "scan_status.json"

    def _write_status(done, n_sens):
        elapsed = time.time() - t_start
        eta = (elapsed / max(done, 1)) * (n_total - done) if done > 0 else 0
        status = {
            "ts": datetime.now().isoformat(),
            "done": done, "total": n_total,
            "n_sensitive": n_sens,
            "elapsed_s": round(elapsed, 1),
            "eta_s": round(eta, 1),
        }
        status_path.write_text(json.dumps(status, indent=2))

    if n_workers <= 1:
        mesh = _get_mesh()
        for i, item in enumerate(work_items):
            flavor, mass, fg, sd = item
            t0 = time.time()
            r = process_mass_point(flavor, mass, mesh,
                                   force_geometry=fg, save_diagnostic=sd)
            elapsed = time.time() - t0
            mass_label = format_mass_for_filename(mass)
            if r is not None:
                results.append(r)
            n_sens = sum(1 for r in results if r.get("has_sensitivity"))
            _write_status(i + 1, n_sens)
            print(f"  [{i+1}/{n_total}] {flavor}/mN_{mass_label} "
                  f"({elapsed:.1f}s)", flush=True)
    else:
        with ProcessPoolExecutor(
            max_workers=n_workers, initializer=_worker_init
        ) as pool:
            futures = {
                pool.submit(_worker_process_point, item): i
                for i, item in enumerate(work_items)
            }
            done_count = 0
            for future in as_completed(futures):
                done_count += 1
                r = future.result()
                if r is not None:
                    results.append(r)
                n_sens = sum(1 for r in results if r.get("has_sensitivity"))
                _write_status(done_count, n_sens)
                if done_count % 10 == 0 or done_count == n_total:
                    elapsed = time.time() - t_start
                    print(f"  [{done_count}/{n_total}] "
                          f"{n_sens} sensitive, "
                          f"{elapsed:.0f}s elapsed", flush=True)

    total_time = time.time() - t_start

    if not results:
        print("No results produced.")
        return

    results.sort(key=lambda r: (r["flavor"], r["mass_GeV"]))
    df = pd.DataFrame(results)
    out_csv = ANALYSIS_DIR / "hnl_sensitivity.csv"
    df.to_csv(out_csv, index=False)
    print(f"\nResults saved: {out_csv}")

    n_sens = int(df["has_sensitivity"].sum())
    print(f"Sensitivity found at {n_sens}/{len(df)} mass points")
    print(f"Total time: {total_time:.0f}s ({total_time/60:.1f} min)")

    meta = {
        "timestamp": datetime.now().isoformat(),
        "flavors": flavors,
        "n_masses": len(masses),
        "n_workers": n_workers,
        "n_results": len(results),
        "n_sensitive": n_sens,
        "mass_range": [float(min(masses)), float(max(masses))],
        "total_time_s": round(total_time, 1),
        "llp_vectors_dir": str(LLP_VECTORS_DIR),
    }
    (ANALYSIS_DIR / "run_metadata.json").write_text(json.dumps(meta, indent=2))

    plot_exclusion(out_csv, ANALYSIS_DIR)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="HNL sensitivity + (m_N, U^2) money plot")
    parser.add_argument(
        "--flavor", nargs="+", default=None, choices=FLAVORS,
        help=f"Flavors to process (default: {DEFAULT_FLAVORS})")
    parser.add_argument(
        "--mass", nargs="+", type=float, default=None,
        help=f"Specific masses in GeV (default: full grid <= {ANALYSIS_MASS_MAX} GeV)")
    parser.add_argument(
        "--plot-only", action="store_true",
        help="Re-plot from existing results CSV")
    parser.add_argument(
        "--force-geometry", action="store_true",
        help="Recompute geometry cache (ignore existing NPZ)")
    parser.add_argument(
        "--diagnostics", action="store_true",
        help="Save N_signal vs U^2 plots for each mass point")
    parser.add_argument(
        "--workers", type=int, default=3,
        help="Number of parallel workers (default: 3)")
    args = parser.parse_args(argv)

    if args.plot_only:
        csv_path = ANALYSIS_DIR / "hnl_sensitivity.csv"
        if not csv_path.exists():
            print(f"No results file found: {csv_path}")
            return 1
        plot_exclusion(csv_path, ANALYSIS_DIR)
        return 0

    flavors = args.flavor or DEFAULT_FLAVORS
    masses = args.mass or [m for m in MASS_GRID if m <= ANALYSIS_MASS_MAX]

    print("HNL Sensitivity Analysis")
    print(f"  Flavors: {flavors}")
    print(f"  Masses: {len(masses)} points "
          f"({min(masses):.2f} - {max(masses):.2f} GeV)")
    print(f"  Workers: {args.workers}")
    print(f"  Luminosity: {L_INT_PB:.0f} pb^-1 ({L_INT_PB/1e3:.0f} fb^-1)")
    print(f"  Threshold: N_signal >= {N_THRESHOLD}")
    print(f"  Inputs:    {LLP_VECTORS_DIR}")
    print(f"  Outputs:   {ANALYSIS_DIR}")

    run(flavors, masses,
        n_workers=args.workers,
        force_geometry=args.force_geometry,
        save_diagnostics=args.diagnostics)
    return 0


if __name__ == "__main__":
    sys.exit(main())
