#!/usr/bin/env python3
"""Drive the FONLL production-uncertainty band for the HNL exclusion curves.

Runs the production + analysis chain once per *coherent* FONLL variation grid,
reusing the FONLL-independent channels, and leaves one ``hnl_sensitivity.csv``
per variation for ``analysis/combine_band.py`` to turn into boundary ribbons.

Coherence rules (per the variation design):

* **scale / PDF** -- the SAME variation grid is applied to BOTH bottom and
  charm. A scale choice or a single proton-PDF replica is correlated across the
  two heavy flavors, so they must move together.
* **mass** -- bottom and charm masses are INDEPENDENT parameters, so each mass
  variation moves one quark's grid while the other stays central.

FONLL-dependent channels, regenerated per variation:
  ``bottom`` (Bmeson), ``charm`` (Dmeson), ``baryon`` (Bbaryon), ``induced_tau``.
FONLL-independent channels, reused from the central run via hardlinks:
  ``Bc``, ``Kmeson``, ``tau`` (prompt-tau), ``WZ``. (Bc only borrows the bottom
  *shape* with its own SIGMA_BC_PB normalization, so it is held central.)

Each variation runs under its own ``HNL_RUN_TAG`` that embeds a hash of the two
grids' checksums, so a tag can never serve a geometry cache built from a
different grid.

Examples
--------
    # full band (all coherent variations, all flavors, full mass grid)
    # (grids generated by the fonll-nnpdf40 tool; written under tmp/fonll/output)
    python run_variation_band.py --grid-dir tmp/fonll/output

    # quick plumbing test: central + one scale point, one flavor, few masses,
    # FONLL channels only (no MadGraph reuse)
    python run_variation_band.py --variations central scale --flavor Umu \
        --mass 1.0 2.0 --fonll-channels-only --analysis-workers 2
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

HNL_ROOT = Path(__file__).resolve().parent
if str(HNL_ROOT) not in sys.path:
    sys.path.insert(0, str(HNL_ROOT))

from config_mass_grid import MASS_GRID, format_mass_for_filename  # noqa: E402

# run_all channel names regenerated per variation (FONLL-dependent)
FONLL_CHANNELS = ["bottom", "charm", "baryon", "induced_tau"]
# combine-channel label dirs reused from central (FONLL-independent)
REUSE_LABELS = ["Bc", "Kmeson", "tau", "WZ"]

# bottom/charm mass-variation grid tags (must match the campaign's _fmt_float_tag)
_MASS_TAGS = {
    "mb_dn": ("mass_4p5", None),   # m_b = 4.50, charm central
    "mb_up": ("mass_5", None),     # m_b = 5.00, charm central
    "mc_dn": (None, "mass_1p3"),   # m_c = 1.30, bottom central
    "mc_up": (None, "mass_1p7"),   # m_c = 1.70, bottom central
}

GRID_STEM = "fonll_pp14tev_nnpdf40_nlo_as_01180_fonll_meson_dsdpTdy_pt0-50_y-3to3"


def _tmp_dir() -> Path:
    return Path(os.environ.get("HNL_TMP_DIR", HNL_ROOT / "tmp")).expanduser()


def _run_dirs(tag: str) -> tuple[Path, Path, Path]:
    run_dir = _tmp_dir() / "runs" / tag
    return run_dir, run_dir / "llp_4vectors", run_dir / "analysis"


def _grid_path(grid_dir: Path, tag: str, quark: str) -> Path:
    return grid_dir / f"{GRID_STEM}_{tag}_{quark}.dat"


def discover_variations(grid_dir: Path, which: list[str] | None) -> list[dict]:
    """Build the coherent variation list from the campaign manifest."""
    manifest = json.loads((grid_dir / "variation_manifest.json").read_text())
    # index manifest entries by (quark, tag) for checksum lookup
    by_key = {(e["quark"], e["variation_tag"]): e for e in manifest["grids"]}

    def entry(tag, quark):
        e = by_key.get((quark, tag))
        if e is None:
            raise FileNotFoundError(f"manifest has no {quark} grid tagged {tag!r}")
        return e

    tags_present = {t for (_, t) in by_key}
    variations: list[dict] = []

    # central
    cb, cc = entry("central", "bottom"), entry("central", "charm")
    variations.append(dict(name="central", axis="central", direction="0",
                           bottom=cb, charm=cc))

    # scale: same (muR,muF) grid for both quarks
    for tag in sorted(t for t in tags_present if t.startswith("scale_")):
        variations.append(dict(name=tag, axis="scale", direction=tag,
                               bottom=entry(tag, "bottom"), charm=entry(tag, "charm")))

    # pdf: same replica member for both quarks (members >= 1; 0 is the mean)
    pdf_tags = sorted(t for t in tags_present if t.startswith("pdf_"))
    for tag in pdf_tags:
        member = int(tag.split("_")[1])
        if member < 1:
            continue
        variations.append(dict(name=tag, axis="pdf", direction=str(member),
                               bottom=entry(tag, "bottom"), charm=entry(tag, "charm")))

    # mass: independent bottom/charm, one varied while the other stays central
    for name, (btag, ctag) in _MASS_TAGS.items():
        b = entry(btag, "bottom") if btag else cb
        c = entry(ctag, "charm") if ctag else cc
        if (btag and btag not in tags_present) or (ctag and ctag not in tags_present):
            continue
        variations.append(dict(name=name, axis="mass", direction=name,
                               bottom=b, charm=c))

    if which:
        sel = set(which)
        variations = [v for v in variations if v["name"] in sel or v["axis"] in sel]
    return variations


def band_run_tag(v: dict, campaign_config: dict | None = None) -> str:
    h = hashlib.sha256((v["bottom"]["sha256"] + v["charm"]["sha256"]).encode()).hexdigest()[:8]
    tag = f"band_{v['name']}_{h}"
    if campaign_config:
        payload = json.dumps(campaign_config, sort_keys=True, separators=(",", ":"))
        config_hash = hashlib.sha256(payload.encode()).hexdigest()[:8]
        tag += f"_cfg{config_hash}"
    return tag


def _code_revision() -> str:
    """Return the exact worktree revision, marking uncommitted code explicitly."""
    try:
        revision = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=HNL_ROOT,
            text=True, stderr=subprocess.DEVNULL).strip()
        dirty = subprocess.run(
            ["git", "diff", "--quiet", "HEAD", "--", "hnl"],
            cwd=HNL_ROOT, stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL).returncode != 0
        return f"{revision}-dirty" if dirty else revision
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _campaign_config(args, flavors, masses) -> dict:
    return {
        "code_revision": _code_revision(),
        "flavors": list(flavors),
        "masses_GeV": [float(mass) for mass in masses],
        "n_pool": int(args.n_pool),
        "production_seed": int(args.seed),
        "decay_samples": int(args.decay_samples),
        "max_hit_events": args.max_hit_events,
        "event_chunk": args.event_chunk,
        "analysis_seed_salt": args.analysis_seed_salt,
        "track_momentum_cut_GeV": float(os.environ.get("HNL_P_CUT", "0.100")),
        "reuse_from": args.reuse_from,
        "fonll_channels_only": bool(args.fonll_channels_only),
        "wz_nb_core": int(args.wz_nb_core),
    }


def _env_for(v: dict, grid_dir: Path, tag: str) -> dict:
    env = os.environ.copy()
    env["HNL_RUN_TAG"] = tag
    env["HNL_FONLL_BOTTOM_GRID"] = str(_grid_path(grid_dir, v["bottom"]["variation_tag"], "bottom"))
    env["HNL_FONLL_CHARM_GRID"] = str(_grid_path(grid_dir, v["charm"]["variation_tag"], "charm"))
    return env


def _run(cmd: list[str], env: dict, label: str) -> None:
    print(f"  $ {label}: {' '.join(cmd)}", flush=True)
    proc = subprocess.run(cmd, env=env, cwd=str(HNL_ROOT))
    if proc.returncode != 0:
        raise RuntimeError(f"{label} failed (exit {proc.returncode})")


def reuse_central_channels(central_vec: Path, var_vec: Path, flavors, masses,
                           strict: bool) -> int:
    """Hardlink the FONLL-independent channel CSVs from central into a variation.

    Zero-byte closed-channel sentinels are linked too (they are valid). With
    ``strict`` a missing central channel file is an error; otherwise it is
    skipped with a warning (used by --fonll-channels-only smoke tests).
    """
    n = 0
    for flavor in flavors:
        for label in REUSE_LABELS:
            for mass in masses:
                rel = Path(flavor) / label / f"mN_{format_mass_for_filename(mass)}.csv"
                src, dst = central_vec / rel, var_vec / rel
                if not src.exists():
                    if strict:
                        raise FileNotFoundError(f"central channel missing: {src}")
                    continue
                dst.parent.mkdir(parents=True, exist_ok=True)
                if dst.exists() or dst.is_symlink():
                    dst.unlink()
                try:
                    os.link(src, dst)            # hardlink: cheap, integrity-shared
                except OSError:
                    dst.write_bytes(src.read_bytes())   # cross-device fallback: copy
                n += 1
    return n


def run_variation(v, grid_dir, source_vec, flavors, masses, args,
                  campaign_config) -> dict:
    tag = band_run_tag(v, campaign_config)
    run_dir, var_vec, analysis_dir = _run_dirs(tag)
    env = _env_for(v, grid_dir, tag)
    is_central = v["axis"] == "central"
    sens_csv = analysis_dir / "hnl_sensitivity.csv"
    entry = {
        "name": v["name"], "axis": v["axis"], "direction": v["direction"],
        "run_tag": tag,
        "bottom_grid_tag": v["bottom"]["variation_tag"],
        "charm_grid_tag": v["charm"]["variation_tag"],
        "sensitivity_csv": str(sens_csv),
        "configuration": campaign_config,
    }
    # Resume: a finished variation keeps only its small sensitivity CSV; skip it.
    if sens_csv.exists() and not args.force:
        print(f"\n=== variation {v['name']} ({v['axis']}) -> already done, skipping ===",
              flush=True)
        return entry
    # A "full central" run generates the MadGraph channels itself and becomes the
    # reuse source. With --reuse-from, even central only regenerates the FONLL
    # channels and hardlinks the expensive channels from the existing run, so the
    # central and varied curves are statistically consistent (same seed/n_pool,
    # only the grid differs) and MadGraph is never re-run.
    full_central = is_central and not args.reuse_from and not args.fonll_channels_only
    print(f"\n=== variation {v['name']} ({v['axis']}) -> tag {tag} ===", flush=True)

    # 1. production
    prod = [sys.executable, "-u", "run_all.py",
            "--flavor", *flavors, "--n-pool", str(args.n_pool),
            "--workers", str(args.prod_workers), "--seed", str(args.seed),
            "--skip-combine"]
    if args.mass:
        prod += ["--masses", *[str(m) for m in masses]]
    if full_central:
        prod += ["--wz-nb-core", str(args.wz_nb_core)]   # full channel set
    else:
        prod += ["--channels", *FONLL_CHANNELS]
    _run(prod, env, f"production[{v['name']}]")

    # 2. reuse the FONLL-independent channels (whenever we regenerated only FONLL)
    if not full_central and not args.fonll_channels_only:
        n = reuse_central_channels(source_vec, var_vec, flavors, masses, strict=True)
        print(f"  reused {n} channel files (Bc/Kmeson/tau/WZ) from {source_vec}", flush=True)

    # 3. combine (strict: a missing/!=expected channel fails the run)
    combine = [sys.executable, "-u", "-m", "production.combine_channels",
               "--flavor", *flavors]
    if args.mass:
        combine += ["--masses", *[str(m) for m in masses]]
    if args.fonll_channels_only:
        combine += ["--allow-missing"]
    _run(combine, env, f"combine[{v['name']}]")

    # 4. analysis -> hnl_sensitivity.csv
    analyze = [sys.executable, "-u", "-m", "analysis.run_sensitivity",
               "--flavor", *flavors, "--workers", str(args.analysis_workers),
               "--decay-samples", str(args.decay_samples)]
    if args.max_hit_events is not None:
        analyze += ["--max-hit-events", str(args.max_hit_events)]
    if args.event_chunk is not None:
        analyze += ["--event-chunk", str(args.event_chunk)]
    if args.analysis_seed_salt:
        analyze += ["--seed-salt", args.analysis_seed_salt]
    if args.mass:
        analyze += ["--mass", *[str(m) for m in masses]]
    _run(analyze, env, f"analysis[{v['name']}]")

    # Reclaim space: the per-variation 4-vectors (~25 GB) are only needed to
    # produce the tiny sensitivity CSV. Drop them unless asked to keep them.
    if not args.keep_intermediates:
        shutil.rmtree(var_vec, ignore_errors=True)
        print(f"  cleaned {var_vec} (kept analysis/hnl_sensitivity.csv)", flush=True)

    return entry


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--grid-dir", default=os.environ.get(
        "HNL_FONLL_GRID_DIR",
        str(HNL_ROOT / "tmp" / "fonll" / "output")),
        help="directory with the campaign's coherent variation grids + manifest "
             "(generated by the fonll-nnpdf40 tool; default tmp/fonll/output, "
             "override with $HNL_FONLL_GRID_DIR)")
    ap.add_argument("--flavor", nargs="+", default=["Ue", "Umu", "Utau"])
    ap.add_argument("--mass", type=float, nargs="+", default=None,
                    help="restrict to these masses (default: full grid)")
    ap.add_argument("--variations", nargs="+", default=None,
                    help="restrict to variation names or axes (central/scale/pdf/mass)")
    ap.add_argument("--n-pool", type=int, default=100_000)
    ap.add_argument("--seed", type=int, default=42,
                    help="base production RNG seed (default: 42)")
    ap.add_argument("--prod-workers", type=int, default=6)
    ap.add_argument("--analysis-workers", type=int, default=3)
    ap.add_argument(
        "--decay-samples", type=int,
        default=int(os.environ.get("HNL_DECAY_SAMPLES", "100")),
        help="decay positions per selected hit event")
    ap.add_argument(
        "--max-hit-events", type=int,
        default=(int(os.environ["HNL_MAX_HIT_EVENTS"])
                 if os.environ.get("HNL_MAX_HIT_EVENTS") else None),
        help="optional weighted-resampling cap; omit for exact hit evaluation")
    ap.add_argument(
        "--event-chunk", type=int,
        default=(int(os.environ["HNL_EVENT_CHUNK"])
                 if os.environ.get("HNL_EVENT_CHUNK") else None),
        help="exact-hit memory chunk; does not change the statistical sample")
    ap.add_argument(
        "--analysis-seed-salt",
        default=os.environ.get("HNL_ANALYSIS_SEED_SALT", ""),
        help="deterministic salt for independent analysis repeats")
    ap.add_argument("--wz-nb-core", type=int, default=1)
    ap.add_argument("--reuse-from", default=None,
                    help="run tag of an existing complete run whose Bc/Kmeson/tau/WZ "
                         "channels are hardlinked into every variation (incl central), "
                         "so MadGraph is never re-run. Must be a run with CURRENT "
                         "channel physics -- a stale tag silently reuses old WZ/Bc/etc.")
    ap.add_argument("--fonll-channels-only", action="store_true",
                    help="smoke test: skip MadGraph/kaon reuse; band uses only the "
                         "4 FONLL channels (incomplete physics, validates plumbing)")
    ap.add_argument("--keep-intermediates", action="store_true",
                    help="keep each variation's llp_4vectors (~25 GB each); default "
                         "deletes them after analysis, keeping only the sensitivity CSV")
    ap.add_argument("--force", action="store_true",
                    help="recompute variations even if their sensitivity CSV exists "
                         "(default: resume by skipping finished variations)")
    ap.add_argument(
        "--registry-out", default=None,
        help="registry output path (default: <HNL_TMP_DIR>/runs/band_registry.json)")
    args = ap.parse_args(argv)

    if args.n_pool < 1:
        ap.error("--n-pool must be >= 1")
    if args.decay_samples < 1:
        ap.error("--decay-samples must be >= 1")
    if args.max_hit_events is not None and args.max_hit_events < 1:
        ap.error("--max-hit-events must be >= 1 when provided")
    if args.event_chunk is not None and args.event_chunk < 1:
        ap.error("--event-chunk must be >= 1 when provided")

    grid_dir = Path(args.grid_dir).expanduser().resolve()
    if not (grid_dir / "variation_manifest.json").exists():
        print(f"no variation_manifest.json under {grid_dir}; run the campaign first")
        return 1

    masses = args.mass if args.mass else list(MASS_GRID)
    variations = discover_variations(grid_dir, args.variations)
    if not variations or variations[0]["axis"] != "central":
        print("variation set must include 'central' (the baseline to reuse from)")
        return 1

    campaign_config = _campaign_config(args, args.flavor, masses)

    print(f"FONLL-variation band: {len(variations)} coherent runs "
          f"({', '.join(v['name'] for v in variations)})")
    print(f"  flavors={args.flavor}  masses={len(masses)}  grids={grid_dir}")
    print(f"  production: n_pool={args.n_pool}, seed={args.seed}")
    hit_note = (f"weighted cap={args.max_hit_events}"
                if args.max_hit_events is not None else "exact all hits")
    print(f"  analysis: decay_samples={args.decay_samples}, {hit_note}, "
          f"event_chunk={args.event_chunk}")

    # Source of the reused MadGraph/kaon channels: an existing complete run if
    # --reuse-from is given, else the central band run (which does full production).
    if args.reuse_from:
        _, source_vec, _ = _run_dirs(args.reuse_from)
        if not source_vec.exists():
            print(f"--reuse-from run not found: {source_vec}")
            return 1
        print(f"  reusing Bc/Kmeson/tau/WZ from {source_vec}")
    else:
        _, source_vec, _ = _run_dirs(
            band_run_tag(variations[0], campaign_config))

    registry = []
    reg_path = (Path(args.registry_out).expanduser()
                if args.registry_out else _tmp_dir() / "runs" / "band_registry.json")
    reg_path.parent.mkdir(parents=True, exist_ok=True)

    def write_registry():
        payload = json.dumps(
            {"grid_dir": str(grid_dir), "configuration": campaign_config,
             "flavors": args.flavor, "n_masses": len(masses),
             "variations": registry}, indent=2) + "\n"
        tmp_path = reg_path.with_name(f".{reg_path.name}.tmp")
        tmp_path.write_text(payload)
        tmp_path.replace(reg_path)

    for v in variations:
        registry.append(run_variation(
            v, grid_dir, source_vec, args.flavor, masses, args,
            campaign_config))
        write_registry()

    print(f"\nwrote {reg_path} ({len(registry)} variations)")
    print("next: python -m analysis.combine_band")
    return 0


if __name__ == "__main__":
    sys.exit(main())
