ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_HeavyN_CKM_AllMasses_LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_43 = ', GC_43
      WRITE(*,2) 'GC_86 = ', GC_86
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_135 = ', GC_135
      WRITE(*,2) 'GC_141 = ', GC_141
      WRITE(*,2) 'GC_157 = ', GC_157
      WRITE(*,2) 'GC_174 = ', GC_174
      WRITE(*,2) 'GC_179 = ', GC_179
      WRITE(*,2) 'GC_182 = ', GC_182
      WRITE(*,2) 'GC_188 = ', GC_188
      WRITE(*,2) 'GC_191 = ', GC_191
