# MadGraph HNL Physics Validation Request

**INSTRUCTIONS**: 
1. Run the test command at the bottom to generate outputs
2. Paste the outputs into the marked sections below
3. Copy this ENTIRE file and paste into a new LLM conversation for physics review

---

## Request for Physics Expert LLM

I've implemented a MadGraph pipeline for Heavy Neutral Lepton (HNL) production via electroweak bosons (W/Z) at LHC 14 TeV. The Docker setup and workflow are functional, but I need you to **validate the PHYSICS implementation**.

**Specific concerns:**
1. Are the MadGraph processes defined correctly?
2. Is the param_card structure correct for the `SM_HeavyN_CKM_AllMasses_LO` UFO model?
3. Is my LHE→CSV parser extracting the right physics?
4. Do the cross-sections make sense?

---

## Physics Questions

Please check:

### 1. Process Definition
- Is `generate p p > mu+ n1` the correct syntax for W → μ N production?
- Does this automatically include Z processes, or should they be explicit?
- Are the process tags (@1, @2, @3, @4) correct?

### 2. Param Card Physics
- Is PDG 9900012 the standard code for n1 in this model?
- Should n1 be stable (DECAY = 0) during event generation?
- Are n2/n3 correctly decoupled at 100 TeV mass?
- Is the `Block numixing` structure correct for pure flavor coupling?
- Should mixing be |U|² = 1 or |U| = 1 at generation time?

### 3. LHE Parsing (CRITICAL)
- For process `p p > mu+ n1`, does W/Z appear explicitly in the LHE event record?
- Or is W/Z an internal propagator that I need to reconstruct from ℓ + N 4-vectors?
- How do I distinguish W* (off-shell) from Z in the event record?

### 4. Cross-Section Sanity
- At m_HNL = 15 GeV, |Uμ|² = 1, what σ should I expect?
- Is ~40-60 pb reasonable for W-dominated production?
- How does this compare to inclusive W production at 14 TeV?

### 5. Mass Range
- Is 5-80 GeV the correct EW regime?
- Below what mass do K/D/B mesons dominate over W/Z?

---

## File 1: Process Card (Muon Coupling)

**Location**: `cards/proc_card_muon.dat`

```
####################################################
# Process card for HNL production (muon coupling)
# pp → W± → μ± N1 and pp → Z → νμ N1
# LHC 14 TeV
####################################################

# Import the HeavyN model
import model SM_HeavyN_CKM_AllMasses_LO

# Define the multiparticle sets
define p = g u c d s u~ c~ d~ s~
define j = g u c d s u~ c~ d~ s~

# Generate EW HNL production processes
# Charged current: pp → W+ → μ+ N1 and pp → W- → μ- N1
generate p p > mu+ n1 @1
add process p p > mu- n1 @2

# Neutral current: pp → Z → vm N1 and pp → Z → vm~ N1
add process p p > vm n1 @3
add process p p > vm~ n1 @4

# Output directory (will be set by driver script)
output work/hnl_muon_MASS_PLACEHOLDER -nojpeg
```

**Key question**: Does `p p > mu+ n1` correctly generate W± → μ± N via MadGraph matrix elements?

---

## File 2: Parameter Card Template

**Location**: `cards/param_card_template.dat`

```
######################################################################
## PARAM_CARD AUTOMATICALLY GENERATED BY MG5 FOLLOWING UFO MODEL   ####
######################################################################
##                                                                  ##
##  Width set on Auto will be computed following the information    ##
##        present in the decay.py files of the model.               ##
##        See  arXiv:1402.1178 for more details.                    ##
##                                                                  ##
######################################################################

###################################
## INFORMATION FOR CKMBLOCK
###################################
Block ckmblock 
    1 2.275910e-01 # cabi 
    2 3.508000e-03 # th13 
    3 4.153900e-02 # th23 
    4 1.200000e+00 # del13 

###################################
## INFORMATION FOR MASS
###################################
Block mass 
    1 5.040000e-03 # MD 
    2 2.550000e-03 # MU 
    3 1.010000e-01 # MS 
    4 1.270000e+00 # MC 
    5 4.700000e+00 # MB 
    6 1.733000e+02 # MT 
   11 5.110000e-04 # Me 
   13 1.056600e-01 # MMU 
   15 1.777000e+00 # MTA 
   23 9.118760e+01 # MZ 
   25 1.257000e+02 # MH 
  9900012 MASS_N1_PLACEHOLDER # n1 (HNL mass in GeV)
  9900014 1.000000e+05        # n2 (decoupled - very heavy)
  9900016 1.000000e+05        # n3 (decoupled - very heavy)
## Dependent parameters, given by model restrictions.
## Those values should be edited following the 
## analytical expression. MG5 ignores those values 
## but they are important for interfacing the output of MG5
## to external program such as Pythia.
  12 0.000000e+00 # ve : 0.0 
  14 0.000000e+00 # vm : 0.0 
  16 0.000000e+00 # vt : 0.0 
  21 0.000000e+00 # g : 0.0 
  22 0.000000e+00 # a : 0.0 
  24 7.995123e+01 # w+ : cmath.sqrt(MZ__exp__2/2. + cmath.sqrt(MZ__exp__4/4. - (aEW*cmath.pi*MZ__exp__2)/(Gf*sqrt__2))) 

###################################
## INFORMATION FOR NUMIXING
###################################
Block numixing
    1 VE1_PLACEHOLDER   # VeN1  (electron ↔ N1)
    2 0.000000e+00      # VeN2
    3 0.000000e+00      # VeN3
    4 VMU1_PLACEHOLDER  # VmuN1 (muon ↔ N1)
    5 0.000000e+00      # VmuN2
    6 0.000000e+00      # VmuN3
    7 VTAU1_PLACEHOLDER # VtaN1 (tau ↔ N1)
    8 0.000000e+00      # VtaN2
    9 0.000000e+00      # VtaN3 

###################################
## INFORMATION FOR SMINPUTS
###################################
Block sminputs 
    1 1.279400e+02 # aEWM1 
    2 1.174560e-05 # Gf 
    3 1.184000e-01 # aS (Note: this Parameter is not used if you use a PDF set) 

###################################
## INFORMATION FOR YUKAWA
###################################
Block yukawa 
    1 5.040000e-03 # ymdo 
    2 2.550000e-03 # ymup 
    3 1.010000e-01 # yms 
    4 1.270000e+00 # ymc 
    5 4.700000e+00 # ymb 
    6 1.733000e+02 # ymt 
   11 5.110000e-04 # yme 
   13 1.056600e-01 # ymm 
   15 1.777000e+00 # ymtau 

###################################
## INFORMATION FOR DECAY
###################################
DECAY   6 1.350000e+00 # WT 
DECAY  23 2.495200e+00 # WZ 
DECAY  24 2.085000e+00 # WW 
DECAY  25 4.170000e-03 # WH 
DECAY 9900012 0.000000e+00 # WN1 (n1 stable for event generation)
DECAY 9900014 0.000000e+00 # WN2 (decoupled)
DECAY 9900016 0.000000e+00 # WN3 (decoupled)
## Dependent parameters, given by model restrictions.
## Those values should be edited following the 
## analytical expression. MG5 ignores those values 
## but they are important for interfacing the output of MG5
## to external program such as Pythia.
```

**Key sections**:
- Line 38: `9900012 MASS_N1_PLACEHOLDER` ← Replaced with actual mass (e.g., 15.0)
- Line 39-40: n2, n3 decoupled at 100 TeV
- Lines 59-67: Block numixing ← VE1/VMU1/VTAU1 placeholders replaced with 0 or 1
- Line 93: `DECAY 9900012 0.000000e+00` ← Stable HNL

**Questions**:
- Is PDG 9900012 correct for n1?
- Should numixing values be 0/1 (for |U|) or 0/1 (for |U|²)?

---

## File 3: LHE to CSV Converter (Physics Extraction Logic)

**Location**: `scripts/lhe_to_csv.py`

```python
#!/usr/bin/env python3
"""
LHE to CSV converter for HNL events

Parses LesHouches Event (LHE) files from MadGraph and extracts:
- HNL particles (PDG 9900012 = N1)
- Parent W/Z bosons (PDG 24, -24, 23)
- 4-momenta and event weights

Output CSV format matches analysis pipeline requirements.

Usage:
    python lhe_to_csv.py input.lhe output.csv --mass 15.0 --flavour muon
    python lhe_to_csv.py input.lhe.gz output.csv --mass 15.0 --flavour muon
"""

import sys
import os
import gzip
import argparse
import re
from pathlib import Path


class LHEParser:
    """Parse LesHouches Event (LHE) files and extract HNL events"""

    # PDG codes
    PDG_HNL_N1 = 9900012
    PDG_WPLUS = 24
    PDG_WMINUS = -24
    PDG_Z = 23

    def __init__(self, lhe_path, mass_gev, flavour):
        """
        Initialize LHE parser

        Args:
            lhe_path: Path to LHE file (can be .lhe or .lhe.gz)
            mass_gev: HNL mass in GeV
            flavour: Lepton flavour (electron, muon, tau)
        """
        self.lhe_path = Path(lhe_path)
        self.mass_gev = float(mass_gev)
        self.flavour = flavour

        if not self.lhe_path.exists():
            raise FileNotFoundError(f"LHE file not found: {lhe_path}")

    def _open_lhe(self):
        """Open LHE file (handles both .lhe and .lhe.gz)"""
        if self.lhe_path.suffix == '.gz':
            return gzip.open(self.lhe_path, 'rt', encoding='utf-8')
        else:
            return open(self.lhe_path, 'r', encoding='utf-8')

    def parse_events(self):
        """
        Parse LHE file and yield event dictionaries

        Yields:
            dict with keys:
                - event_id: int
                - parent_pdgid: int (W+/W-/Z)
                - hnl_pdgid: int (N1)
                - mass_hnl_GeV: float
                - weight: float
                - parent_E_GeV, parent_px_GeV, parent_py_GeV, parent_pz_GeV: float
                - hnl_E_GeV, hnl_px_GeV, hnl_py_GeV, hnl_pz_GeV: float
        """
        event_id = 0
        in_event = False
        event_weight = 1.0
        particles = []

        with self._open_lhe() as f:
            for line in f:
                line = line.strip()

                # Start of event block
                if line.startswith('<event>'):
                    in_event = True
                    particles = []
                    event_weight = 1.0
                    continue

                # End of event block
                if line.startswith('</event>'):
                    in_event = False
                    event_id += 1

                    # Extract HNL and parent information
                    event_data = self._extract_hnl_and_parent(
                        particles, event_id, event_weight
                    )

                    if event_data is not None:
                        yield event_data

                    continue

                # Parse event content
                if in_event:
                    # First line after <event> is event header
                    if len(particles) == 0 and not line.startswith('#'):
                        # Event header format: nup idprup xwgtup scalup aqedup aqcdup
                        parts = line.split()
                        if len(parts) >= 3:
                            event_weight = float(parts[2])  # xwgtup

                    # Particle lines
                    elif not line.startswith('#') and line:
                        parts = line.split()
                        if len(parts) >= 11:
                            try:
                                particle = {
                                    'pdgid': int(parts[0]),
                                    'status': int(parts[1]),
                                    'mother1': int(parts[2]),
                                    'mother2': int(parts[3]),
                                    'px': float(parts[6]),
                                    'py': float(parts[7]),
                                    'pz': float(parts[8]),
                                    'E': float(parts[9]),
                                    'mass': float(parts[10]),
                                }
                                particles.append(particle)
                            except (ValueError, IndexError):
                                # Skip malformed lines
                                pass

        print(f"Parsed {event_id} events from {self.lhe_path.name}")

    def _extract_hnl_and_parent(self, particles, event_id, weight):
        """
        Extract HNL and its parent W/Z from particle list

        Args:
            particles: List of particle dicts
            event_id: Event number
            weight: Event weight

        Returns:
            dict with event data, or None if no HNL found
        """
        # Find HNL (N1)
        hnl = None
        for i, p in enumerate(particles):
            if p['pdgid'] == self.PDG_HNL_N1:
                hnl = p
                hnl_index = i + 1  # LHE uses 1-based indexing
                break

        if hnl is None:
            return None

        # Find parent W/Z using mother indices
        parent = None
        mother1_idx = hnl['mother1']

        if 1 <= mother1_idx <= len(particles):
            parent_candidate = particles[mother1_idx - 1]
            if parent_candidate['pdgid'] in [self.PDG_WPLUS, self.PDG_WMINUS, self.PDG_Z]:
                parent = parent_candidate

        # If direct mother is not W/Z, search all particles
        # (sometimes there are intermediate resonances)
        if parent is None:
            for p in particles:
                if p['pdgid'] in [self.PDG_WPLUS, self.PDG_WMINUS, self.PDG_Z]:
                    # Check if this W/Z is outgoing (status 1) or intermediate (status 2)
                    parent = p
                    break

        if parent is None:
            # No W/Z found - this shouldn't happen for our processes
            # but handle gracefully
            print(f"Warning: Event {event_id} has HNL but no W/Z parent found")
            return None

        # Build event data dictionary
        return {
            'event_id': event_id,
            'parent_pdgid': parent['pdgid'],
            'hnl_pdgid': hnl['pdgid'],
            'mass_hnl_GeV': self.mass_gev,
            'weight': weight,
            'parent_E_GeV': parent['E'],
            'parent_px_GeV': parent['px'],
            'parent_py_GeV': parent['py'],
            'parent_pz_GeV': parent['pz'],
            'hnl_E_GeV': hnl['E'],
            'hnl_px_GeV': hnl['px'],
            'hnl_py_GeV': hnl['py'],
            'hnl_pz_GeV': hnl['pz'],
        }

    def write_csv(self, output_path):
        """
        Parse LHE and write CSV file

        Args:
            output_path: Path to output CSV file

        Returns:
            int: Number of events written
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # CSV header (EXACT format required by analysis pipeline)
        header = "event_id,parent_pdgid,hnl_pdgid,mass_hnl_GeV,weight,parent_E_GeV,parent_px_GeV,parent_py_GeV,parent_pz_GeV,hnl_E_GeV,hnl_px_GeV,hnl_py_GeV,hnl_pz_GeV"

        n_events = 0
        with open(output_path, 'w') as f:
            f.write(header + '\n')

            for event in self.parse_events():
                # Write CSV row
                row = (
                    f"{event['event_id']},"
                    f"{event['parent_pdgid']},"
                    f"{event['hnl_pdgid']},"
                    f"{event['mass_hnl_GeV']:.1f},"
                    f"{event['weight']:.6e},"
                    f"{event['parent_E_GeV']:.6e},"
                    f"{event['parent_px_GeV']:.6e},"
                    f"{event['parent_py_GeV']:.6e},"
                    f"{event['parent_pz_GeV']:.6e},"
                    f"{event['hnl_E_GeV']:.6e},"
                    f"{event['hnl_px_GeV']:.6e},"
                    f"{event['hnl_py_GeV']:.6e},"
                    f"{event['hnl_pz_GeV']:.6e}"
                )
                f.write(row + '\n')
                n_events += 1

        print(f"Wrote {n_events} HNL events to {output_path}")
        return n_events


def main():
    """Command-line interface"""
    parser = argparse.ArgumentParser(
        description='Convert LHE file to CSV for HNL analysis'
    )
    parser.add_argument(
        'lhe_file',
        help='Input LHE file (.lhe or .lhe.gz)'
    )
    parser.add_argument(
        'csv_file',
        help='Output CSV file'
    )
    parser.add_argument(
        '--mass',
        type=float,
        required=True,
        help='HNL mass in GeV'
    )
    parser.add_argument(
        '--flavour',
        choices=['electron', 'muon', 'tau'],
        required=True,
        help='Lepton flavour'
    )

    args = parser.parse_args()

    # Parse and convert
    lhe_parser = LHEParser(args.lhe_file, args.mass, args.flavour)
    n_events = lhe_parser.write_csv(args.csv_file)

    print(f"\nConversion complete:")
    print(f"  Input:  {args.lhe_file}")
    print(f"  Output: {args.csv_file}")
    print(f"  Events: {n_events}")
    print(f"  Mass:   {args.mass} GeV")
    print(f"  Flavour: {args.flavour}")

    return 0


if __name__ == '__main__':
    sys.exit(main())
```

**CRITICAL SECTION**: `_extract_hnl_and_parent()` method (lines 134-196)

This function:
1. Finds HNL with PDG 9900012
2. Looks for parent W/Z using mother indices
3. Falls back to searching all particles for W/Z

**Questions**:
- For `p p > mu+ n1`, is W/Z explicitly in the particle list?
- Or is it an internal propagator that won't appear?
- Should I instead reconstruct W from μ + N 4-vectors?
- How reliable is the mother index approach?

---

## File 4: UFO Model Context

**Model**: `SM_HeavyN_CKM_AllMasses_LO` (auto-downloaded from FeynRules)

**Particle Content**:
- n1 (PDG 9900012): Active HNL, mass = scan parameter
- n2 (PDG 9900014): Decoupled, mass = 100 TeV
- n3 (PDG 9900016): Decoupled, mass = 100 TeV

**Mixing Structure**:
- `Block numixing`: 3×3 matrix (n1, n2, n3) × (e, μ, τ)
- For pure muon coupling: VeN1=0, VmuN1=1, VtaN1=0, all others=0

**Physics**:
- Processes: pp → W → ℓ N and pp → Z → ν N
- Production via EW vertices with mixing suppression
- Cross-section ∝ |U_ℓ|²

---

## PASTE TEST OUTPUTS BELOW (Generate First)

### How to Generate Test Output

Run this command from the repository root:

```bash
docker run --rm -v "$(pwd)":/work mg5-hnl bash -c \
  "cd /work/production/madgraph && \
   python3 scripts/run_hnl_scan.py --masses 15 --flavour muon --nevents 100"
```

Then execute these commands to extract the data:

```bash
# 1. View substituted param_card
cat production/madgraph/work/hnl_muon_15.0GeV/Cards/param_card.dat | grep -A5 "Block mass" | grep 9900012

cat production/madgraph/work/hnl_muon_15.0GeV/Cards/param_card.dat | grep -A10 "Block numixing"

# 2. Extract sample LHE events (first 150 lines including 1-2 full events)
gunzip -c production/madgraph/work/hnl_muon_15.0GeV/Events/run_01/unweighted_events.lhe.gz | head -150

# 3. View CSV output
head -20 production/madgraph/csv/muon/HNL_mass_15.0GeV_muon_EW.csv

# 4. View cross-section summary
cat production/madgraph/csv/summary_HNL_EW_production.csv
```

---

### Output 1: Substituted Param Card (Mass Block)

**PASTE OUTPUT FROM COMMAND 1 HERE:**

```
[PASTE: cat production/madgraph/work/hnl_muon_15.0GeV/Cards/param_card.dat | grep -A5 "Block mass" | grep 9900012]
```

**Expected**: Should show `9900012 1.500000e+01` (mass = 15 GeV)

---

### Output 2: Substituted Param Card (Mixing Block)

**PASTE OUTPUT HERE:**

```
[PASTE: cat production/madgraph/work/hnl_muon_15.0GeV/Cards/param_card.dat | grep -A10 "Block numixing"]
```

**Expected**: 
- Entry 1 (VeN1) = 0.000000e+00
- Entry 4 (VmuN1) = 1.000000e+00
- Entry 7 (VtaN1) = 0.000000e+00

---

### Output 3: Sample LHE Events (First 150 Lines)

**PASTE OUTPUT HERE:**

```
[PASTE: gunzip -c production/madgraph/work/hnl_muon_15.0GeV/Events/run_01/unweighted_events.lhe.gz | head -150]
```

**What to check**:
- Does the event contain particles with PDG 9900012 (n1)?
- Does it contain PDG ±13 (muon)?
- Does it contain PDG 24, -24, or 23 (W/Z)?
- What is the particle status code for W/Z?
- What are the mother indices for the HNL?

---

### Output 4: CSV Output (First 20 Rows)

**PASTE OUTPUT HERE:**

```
[PASTE: head -20 production/madgraph/csv/muon/HNL_mass_15.0GeV_muon_EW.csv]
```

**What to check**:
- Column 2 (parent_pdgid): Should be 24, -24, or 23
- Column 3 (hnl_pdgid): Should be 9900012
- Column 4 (mass_hnl_GeV): Should be 15.0
- Are the 4-momenta physical? (E² ≈ p² + m² for each particle)

---

### Output 5: Cross-Section Summary

**PASTE OUTPUT HERE:**

```
[PASTE: cat production/madgraph/csv/summary_HNL_EW_production.csv]
```

**Expected**: σ ~ 40-60 pb for 15 GeV muon coupling at |Uμ|² = 1

**What to check**:
- Is the cross-section in the expected range?
- Does it scale correctly with mass (higher mass → lower σ)?

---

## Additional Context: Physics Methodology

### Production Mechanism

**Low mass (m < 5 GeV)**: Meson production dominates
- K → ℓ N (m < 0.5 GeV)
- D → ℓ N (0.5 < m < 2 GeV)  
- B → ℓ N (2 < m < 5 GeV)
- (Handled by separate Pythia pipeline)

**High mass (m ≥ 5 GeV)**: Electroweak production dominates (this pipeline)
- pp → W* → ℓ N (dominant)
- pp → Z* → ν N (subdominant, ~25% of W)
- Cross-sections: σ(W) ~ 3-4 × σ(Z)

### Cross-Section Expectations

At LHC 14 TeV with |U_ℓ|² = 1:

| m_HNL [GeV] | σ_total [pb] | Dominant |
|-------------|--------------|----------|
| 5           | ~100         | W        |
| 10          | ~70          | W        |
| 15          | ~50          | W        |
| 30          | ~20          | W        |
| 60          | ~3           | W        |
| 80          | ~0.5         | W        |

**Reference**: Inclusive W production at 14 TeV ~ 200 nb (200,000 pb)

### Mixing Convention

The code sets mixing parameter to 1 (not |U|² = 1) in the param_card:
```
VmuN1 = 1.000000e+00
```

**Question**: Is this correct, or should it be the square root?

In HNL physics:
- Cross-section ∝ |U_ℓ|²
- Lifetime ∝ 1/|U_ℓ|²

**Interpretation**:
- If param_card has `VmuN1 = 1.0`, does this mean |U| = 1 or |U|² = 1?
- MadGraph computes σ from this, so which convention does the UFO model use?

---

## Summary of Physics Validation Needed

Please review the above files and outputs and check:

1. **Process definition**: Correct MadGraph syntax for W/Z → ℓ N?
2. **Param card**: PDG codes, mixing structure, decoupling strategy?
3. **LHE parsing**: Is the W/Z extraction method correct?
4. **Cross-sections**: Do the values make physical sense?
5. **Mixing convention**: |U| = 1 or |U|² = 1 in the param_card?

**Most critical**: The LHE parsing logic (File 3, lines 134-196). Is it correctly extracting the parent W/Z from the event record, or should I be reconstructing it?

Thank you for the physics review!

---

## End of Document

**REMEMBER**: 
1. Generate test output using the Docker command above
2. Paste outputs into marked sections
3. Copy this entire document to physics expert LLM

